name: Build & Release

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - build.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          docker login docker.pkg.github.com -u nchlswhttkr -p ${{ secrets.GITHUB_TOKEN }}
          docker build \
            -t docker.pkg.github.com/nchlswhttkr/hugo-compress/hugo-compress:${{ github.sha }} \
            -t docker.pkg.github.com/nchlswhttkr/hugo-compress/hugo-compress:latest .
          docker push docker.pkg.github.com/nchlswhttkr/hugo-compress/hugo-compress:${{ github.sha }}
          docker push docker.pkg.github.com/nchlswhttkr/hugo-compress/hugo-compress:latest
